# This docker file build a editable image.
# You could directly edit the source code at `/home/brkraw to make changes. Or you could mount your brkraw code folder to /home/brkraw

# HOW TO USE:
# CHANGE THIS FILENAME TO Dockerfile
# 1: BUILD IMAGE: run 'docker build . -t <IMAGE_NAME>'
# 2: docker run -it -e DISPLAY=$DISPLAY     \
#    -u=$(id -u $USER):$(id -g $USER)       \
#    -v /tmp/.X11-unix:/tmp/.X11-unix:rw    \
#    -v /<DATA_PATH>:/data
#    --rm <IMAGE_NAME> brkraw <command>     

FROM python:3.9

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git 
RUN apt-get install -y make gcc libfftw3-dev liblapacke-dev libpng-dev libopenblas-dev
RUN apt-get install tk -y
RUN rm -rf /var/lib/apt/lists/*

#BART
RUN wget https://github.com/mrirecon/bart/archive/refs/tags/v0.9.00.tar.gz \
&& tar zxvpf v0.9.00.tar.gz && rm v0.9.00.tar.gz
WORKDIR /bart-0.9.00
RUN make
WORKDIR /
RUN echo '[Default]\ntoolbox_path = /bart-0.9.00/' > /root/.brkbartrc
ENV TOOLBOX_PATH=/bart-0.9.00
ENV PATH=$TOOLBOX_PATH:$PATH

# INSTALL BRKRAW
WORKDIR /home
RUN mkdir ./brkraw
WORKDIR /home/brkraw

# COPY is not working currently
COPY . .

# RUN git clone only clones files 
# into current dir not into separte dir
#RUN git clone https://github.com/timwahoo/brkraw.git .
RUN python -m pip install --editable /home/brkraw

# INSTALL BRKRAW-BART
WORKDIR /home
RUN mkdir ./brkraw-bart
WORKDIR /home/brkraw-bart
RUN git clone https://github.com/timwahoo/brkraw-bart.git .
RUN python setup.py install

RUN mkdir /data
WORKDIR /data

CMD echo '--------------------'; \
    echo 'To use the bids converter:'; \
    echo 'first run bids_helper'; \
    echo 'brkraw bids_helper <input dir> <output filename> -j'; \
    echo 'second, run converter'; \
    echo 'brkraw bids_convert <input dir> <BIDS datasheet.xlsx> -j <JSON syntax template.json> -o <output dir>';\
    echo '--------------------'; \
    bash

